[package]
name = "actix_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
derive_more = { version = "1.0", features = ["display", "error"] }
serde = { version = "1.0.205", features = ["derive"] }
